### ISSUE TITLE
Display Important Facts in an Easy to Read Table

### ISSUE THREAD

**Issue by aryanindarapu** [aryanindarapu/Fantasy-2020#4]
Using the Blue Alliance API, it is important to display everything in a table that any user can understand.

NOTE: It is CRUCIAL that these data/stats are universal in every game (e.g. OPR, W-L-T records). This allows for easy integration into this year's game.

**Comment by InsanityMatrix** [comment]
Formatted data output into tables, but we should design the tables, use the first row as the header row as there is no <th>
